### ISSUE TITLE
roadmap.md missing

### ISSUE THREAD

**Issue by benhalverson** [kentcdodds/webpack-config-utils#10]
The roadmap.md file is missing

**Comment by kentcdodds** [comment]
Nope, it's just in `other` so I don't clutter up the root directory as much :)

https://github.com/kentcdodds/webpack-config-utils/blob/master/other/ROADMAP.md

And the link on the README is correct. Thanks for caring!

**Comment by benhalverson** [comment]
i just saw that 👍
