### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by nmaves** [kentcdodds/webpack-config-utils#2]
I see in the docs the use of `here` in the following line but I don't see it anywhere in the source. 

`const {getIfUtils, here} = require('webpack-config-utils')`

**Comment by kentcdodds** [comment]
Oh yes, that was removed because it served little purpose. Would you like to submit a pull request to fix the docs? [makeapullrequest.com](http://makeapullrequest.com)

**Comment by nmaves** [comment]
Closed per #3
