### ISSUE TITLE
Prototype Override Protection Bypass

### ISSUE THREAD

**Issue by vernondegoede** [kentcdodds/webpack-config-utils#21]
This package depends on `webpack-combine-loaders`, which depends on `qs` `5.2.1`. 

The `qs` package has a known vulnerability: https://snyk.io/vuln/npm:qs:20170213.

I created a PR for https://github.com/jsdf/webpack-combine-loaders/pull/10. Once a new version has been released, its version should be bumped for this package as well.

**Comment by kentcdodds** [comment]
Sounds great. Could you make a PR here when that happens? Thank you!

**Comment by vernondegoede** [comment]
Sure!

**Comment by vernondegoede** [comment]
@kentcdodds I just released v2.0.4 of `webpack-combine-loaders`, which fixes this issue.

https://github.com/jsdf/webpack-combine-loaders/releases/tag/v2.0.4
