### ISSUE TITLE
Docs site has expired certificate

### ISSUE THREAD

**Issue by hypothete** [kentcdodds/webpack-config-utils#24]
It appears that the SSL cert for https://doclets.io/kentcdodds/webpack-config-utils/master has expired. Just thought you might want to take a look at that.

**Comment by kentcdodds** [comment]
That site never worked. I'd rather just remove all references to it. Want to make a PR?

**Comment by gitKendra** [comment]
Is there a different site for the docs that I can replace it with?

**Comment by kentcdodds** [comment]
There is not.

We should probably add API docs to the README.md
