### ISSUE TITLE
Configurable ifXXX

### ISSUE THREAD

**Issue by rrag** [kentcdodds/webpack-config-utils#7]
I usually have a dev, prod and watch build, 

- watch has `hmr` entrypoints, `hmr` plugin, no uglify and `eval` as `devtool`
- dev has no uglify plugin, `sourcemap` devtool
- prod has uglify plugin, `sourcemap` devtool

Now it seems it is not possible to do a `ifWatch`
https://github.com/kentcdodds/webpack-config-utils/blob/master/src/get-if-utils.js#L43

How about make this configurable and default to this current 
```
const vars = ['production', 'prod', 'test', 'development', 'dev']
```

I am thinking something like

```diff
...
 * `process.env.NODE_ENV`.
 * @return {IfUtils} the IfUtils object for the given environment
 */
+ function getIfUtils(env, vars = ['production', 'prod', 'test', 'development', 'dev']) {
- function getIfUtils(env) {
  env = typeof env === 'string' ? {[env]: true} : env
  if (typeof env !== 'object') {
...
    )
  }
-  const vars = ['production', 'prod', 'test', 'development', 'dev']
  return vars.reduce((utils, variable) => {
    const envValue = !!env[variable]
    const capitalVariable = capitalizeWord(variable)
...
```

so now I can do

```js
const { ifProduction, ifDev, ifWatch } = getIfUtils(mode, ['production', 'dev', 'watch'])
```

**Comment by kentcdodds** [comment]
Sounds great! Would you like to [makeapullrequest.com](http://makeapullrequest.com)? :-)

**Comment by rrag** [comment]
will do, sorry for delay
