### ISSUE TITLE
Thoughts on upgrading this to use ES6 and webpack 2?

### ISSUE THREAD

**Issue by nmaves** [kentcdodds/webpack-config-utils#9]
I would gladly help out just not sure if you want to move that way or not.

**Comment by kentcdodds** [comment]
This actually works with ES6 and webpack 2. Can you give me an example use case where it doesn't?

**Comment by nmaves** [comment]
That was terrible wording.  I should have asked if we wanted to add ES6 and webpack 2 docs.

**Comment by kentcdodds** [comment]
Oh! Yes! Let's improve that. There's a tiny blurb about Webpack 2 in the README, but it could be improved. Would you like to [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by nmaves** [comment]
I can :)

**Comment by kentcdodds** [comment]
Awesome! Don't forget to [add yourself to the list of contributors](https://github.com/kentcdodds/webpack-config-utils/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) :)
